spring.application.name=DEMP

# logging.file.name=logs/application.log

# Control verbosity globally or per package
logging.level.root=INFO
logging.level.com.wipro.demp=DEBUG
spring.output.ansi.enabled=ALWAYS

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/event_management_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root123
 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
 
jwt.secret=+YIsZn3SvkyK0mw7La+WkVFFqyjbrM/DbbQh8eecVfE=
 
jwt.expiration=36000000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=event.notifications2025@gmail.com
spring.mail.password=fkutcrwlpnlvtcee
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# spring.mail.properties.mail.smtp.ssl.enable=true
# spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
# spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

razorpay.keyId=rzp_test_SMe0bOErmp8QoC
razorpay.keySecret=NS0eCig4x78ILkfeq38WKFUu