spring.application.name=DEMP

server.port=8083

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DEMP_DB_URL:jdbc:mysql://localhost:3306/identity_db?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${DEMP_DB_USERNAME:root}
spring.datasource.password=${DEMP_DB_PASSWORD:root123}
 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
 
#admin.service.url=http://ADMIN

jwt.secret=${JWT_SECRET:cPDiUiq1/3iUlBjDYl7SbFjuW74chZ/uOtWiSCSsK5g=}
jwt.expiration=${JWT_EXPIRATION:36000000}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:event.notifications2025@gmail.com}
spring.mail.password=${MAIL_PASSWORD:fkutcrwlpnlvtcee}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true