spring.application.name=organizer-service
server.port=8088

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

jwt.secret=+YIsZn3SvkyK0mw7La+WkVFFqyjbrM/DbbQh8eecVfE=

logging.level.com.wipro.organizerservice=DEBUG
