spring.application.name=TICKETS

server.port=8083

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/event_management_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=cPDiUiq1/3iUlBjDYl7SbFjuW74chZ/uOtWiSCSsK5g=

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.registry-fetch-interval-seconds=30
eureka.instance.lease-renewal-interval-in-seconds=30

services.demp.base-url=http://DEMP
services.event.base-url=http://EVENT

resilience4j.retry.instances.userServiceValidation.maxAttempts=3
resilience4j.retry.instances.userServiceValidation.waitDuration=300ms
resilience4j.retry.instances.userServiceValidation.enableExponentialBackoff=true
resilience4j.retry.instances.userServiceValidation.exponentialBackoffMultiplier=2
resilience4j.retry.instances.userServiceValidation.retryExceptions=org.springframework.web.client.RestClientException,java.lang.IllegalStateException

resilience4j.retry.instances.eventServiceValidation.maxAttempts=3
resilience4j.retry.instances.eventServiceValidation.waitDuration=300ms
resilience4j.retry.instances.eventServiceValidation.enableExponentialBackoff=true
resilience4j.retry.instances.eventServiceValidation.exponentialBackoffMultiplier=2
resilience4j.retry.instances.eventServiceValidation.retryExceptions=org.springframework.web.client.RestClientException,java.lang.IllegalStateException

resilience4j.circuitbreaker.instances.userServiceValidation.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userServiceValidation.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.userServiceValidation.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.userServiceValidation.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userServiceValidation.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.userServiceValidation.permittedNumberOfCallsInHalfOpenState=3

resilience4j.circuitbreaker.instances.eventServiceValidation.failureRateThreshold=50
resilience4j.circuitbreaker.instances.eventServiceValidation.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.eventServiceValidation.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.eventServiceValidation.slidingWindowSize=10
resilience4j.circuitbreaker.instances.eventServiceValidation.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.eventServiceValidation.permittedNumberOfCallsInHalfOpenState=3
